version: '3.8'

volumes:
  redis-data:

services:
  common: &common
    #image: noimage
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8091:8091"
    expose:
      - "8091"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ${USERHOME}/.bittensor/wallets:/root/.bittensor/wallets
      - .:/install
      - ${REDIS_CONF}:/etc/redis/redis.conf

  filetao-prod:
    <<: *common
    build:
      target: filetao-prod
    container_name: filetao-prod
    command:
      - /bin/bash
      - -c
      - |
        filetao run ${FILETAO_NODE} \
          --wallet.name ${FILETAO_WALLET}  \
          --wallet.hotkey ${FILETAO_HOTKEY} \
          --netuid ${FILETAO_NETUID} \
          --subtensor.network ${FILETAO_SUBTENSOR} \
          --wandb.off --logging.debug \
          --database.host redis --database.redis_password $REDIS_PASSWORD

  redis:
    build:
      context: .
      args:
        REDIS_CONF: ${REDIS_CONF}
      dockerfile: Dockerfile.redis
    container_name: redis
    restart: always
    command:
      - redis-server
      - /etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
      #- ${REDIS_CONF}:/etc/redis/redis.conf
